config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  # ... other routes in your application

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "splash#index"

  resources :entities, only: [:index, :new, :create, :show, :destroy, :edit, :update, :all]

  resources :groups, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  resources :users, only: [:index, :new, :create, :show, :destroy, :edit, :update]

end

app/models/entity.rb
class Entity < ApplicationRecord
  include ActiveModel::Validations
  belongs_to :user, class_name: 'User', foreign_key: :author_id
  # has_and_belongs_to_many :groups
  has_many :group_entities, dependent: :destroy
  has_many :groups, through: :group_entities

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def self.most_recent(user, limit = nil)
    limit ||= user.entities.count
    where(user:).order(created_at: :desc).limit(limit)
  end

  def self.most_ancient(user, limit = nil)
    limit ||= user.entities.count
    where(user:).order(created_at: :asc).limit(limit)
  end

  def self.entities_by_user(user)
    where(user:).order(created_at: :desc)
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entity, only: %i[show edit update destroy]

  def index
    @recent_entities = Entity.most_recent(current_user).includes(:groups)
    @ancient_entities = Entity.most_ancient(current_user).includes(:groups)
  end

  def all(_index)
    @entities = Entity.all
  end

  def show; end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entity_params.merge(author_id: current_user.id))

    @entity.groups << Group.find(params[:entity][:group_id]) if params[:entity][:group_id].present?

    if @entity.save
      redirect_to @entity, notice: 'Entity was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @entity.update(entity_params)
      redirect_to @entity, notice: 'Entity was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @entity = Entity.find(params[:id])
    if @entity.destroy
      redirect_to entities_path, notice: 'Entity was successfully destroyed.'
    else
      flash[:alert] = 'Error destroying entity.'
      render :show
    end
  end

  def most_recent
    @recent_entities = Entity.most_recent(current_user)
  end

  def most_ancient
    @ancient_entities = Entity.most_ancient(current_user)
  end

  private

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount, group_ids: [])
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_entity.html.erb
<li class="group-item">
  <div class="group-details">
    <div class="group-i">
      <% if @entity.groups.any? %>
        <% group_icon = @entity.groups.first.icon %>
        <%= image_tag(group_icon.present? ? group_icon : 'default.png', alt: 'GroupIcon', class: "group-icon") %> 
      <% else %>
        <%= image_tag 'default.png', alt: 'Default Icon', class: "group-icon" %>
      <% end %>
      <div class="group-inners">
        <%= link_to @entity.name, @entity, class: "group-name"%>
        <p class="created-at">
          <%= @entity.created_at.strftime('%Y-%m-%d %H:%M:%S') %>
        </p>
      </div>
    </div>
    <p class="group-info"><%= format_currency(@entity.amount) %></p>
  </div>
</li>

app/views/entities/_form.html.erb
<br />
<div class="group-item form-item">
<%= form_with(model: entity, local: true) do |form| %>
  <% if entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entity.errors.count, 'error') %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:group_id].present? %>
    <%= form.hidden_field :group_id, value: params[:group_id] %>
  <% else %>
    <div class="field-select">
      <%= form.label :Select_categories %>
      <%= form.collection_check_boxes(:group_ids, current_user.groups, :id, :name) do |group_checkbox| %>
  <div class="checkbox-item">
    <%= group_checkbox.check_box %>
    <%= group_checkbox.label %>
  </div>
<% end %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "groceries"%>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, placeholder: "0.00" %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit' %>
  </div>
<% end %>
</div>

<br />

app/views/entities/_toggle_buttons.html.erb
<% if request.path == '/entities' %>
<div class="container row">
  <div id="toggle-buttons" class="mt-2 text-right">
    <button id="ancient-toggle" type="button">Latter</button>
    <button id="recent-toggle" type="button" class="short-line">Recent</button>
  </div>
<div>
<% end %>

app/views/entities/all.html.erb
<h1>All Entities</h1>

<% if @entities.any? %>
  <ul class="entities-collections">
    <% @entities.each do |entity| %>
      <% @entity = entity %>
      <%= render partial: 'entity' %>
    <% end %>
  </ul>
<% else %>
  <p>No entities found.</p>
<% end %>

<%= link_to 'New Entity', new_entity_path, class: "link-to-new" %>

app/views/entities/edit.html.erb
<%= render 'form', entity: @entity %>

<%= link_to 'Back', entity_path(@entity) %>

app/views/entities/index.html.erb
  <div class="row">

<div id="entity-list">
  <div id="recent-entities" style="display: block;">
    <ul class="entities-collections">
      <% @recent_entities.each do |entity| %>
        <% @entity = entity %>
        <%= render partial: 'entity' %>
      <% end %>
    </ul>
  </div>

  <div id="ancient-entities" style="display: none;">
    <ul class="entities-collections">
      <% @ancient_entities.each do |entity| %>
        <% @entity = entity %>
        <%= render partial: 'entity' %>
      <% end %>
    </ul>
  </div>
</div>
</div>
<div class = "new-group-link">
  <%= link_to 'Add a new transaction', new_entity_path, class: "new-group-link-inner" %>
<div>

<br>

app/views/entities/new.html.erb
<%= render 'form', entity: @entity %>

<%= link_to 'All transactions', entities_path %>

app/views/entities/show.html.erb
<div class="entity-detail">
  <div class="entity-i">
    <% if @entity.groups.any? %>
        <% group_icon = @entity.groups.first.icon %>
        <%= image_tag(group_icon.present? ? group_icon : 'default.png', alt: 'GroupIcon', class: "group-icon") %> 
    <% else %>
        <%= image_tag 'default.png', alt: 'Default Icon', class: "group-icon" %>
    <% end %>

    <h2 class="group-name-nl"><%= @entity.name %></h2>
  </div>

  <p class="transaction-amount">
    transaction Amount: <span> <%= format_currency(@entity.amount) %> </span>
  </p>

  <p class="created-at"><%= @entity.created_at %></p>

  <div>
      <% if @entity.groups.any? %>
          <h3 class="h3-title"> Categories: </h3>
          <%= @entity.groups.map { |group| link_to("\##{group.name}", group_path(group), class: "group-name-sm") }.join(' | ').html_safe %>
      <% end %> 
  </div>

  <hr>

  

  <% if @entity.user == current_user %>
    <div>
      <%= link_to 'Edit', edit_entity_path(@entity), class: "action-link" %>|
      <%= link_to 'Add transaction', new_entity_path, class: "action-link" %>|
      <%= link_to 'Delete', entity_path(@entity), method: :delete, data: { confirm: 'Are you sure you want to delete this group?' }, class: "action-link" %>
    </div>
  <% end %>

  <%= link_to 'All transaction', entities_path, class: "action-link" %>
</div>

<br>