config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  # ... other routes in your application

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "splash#index"

  resources :entities, only: [:index, :new, :create, :show, :destroy, :edit, :update, :all]

  resources :groups, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  resources :users, only: [:index, :new, :create, :show, :destroy, :edit, :update]

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  has_many :group_entities, dependent: :destroy
  has_many :entities, through: :group_entities

  has_one_attached :icon

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validate :valid_icon_format

  before_validation :set_default_icon

  def self.descending_order_for_user(user)
    where(user:).order(created_at: :desc)
  end

  private

  def valid_icon_format
    return unless icon.attached? && icon.blob.present?

    allowed_formats = %w[image/png image/gif image/jpeg image/jpg image/svg+xml]
    return if allowed_formats.include?(icon.blob.content_type)

    errors.add(:icon, 'Field only accepts png, gif, jpeg, jpg, or svg.')
  end

  def set_default_icon
    self.icon ||= 'default.png'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = current_user.groups.includes(:entities)
    @total_entities_count = @groups.sum { |group| group.entities.size }
    @total_entities_sum = @groups.sum { |group| group.entities.sum(:amount) }
  end

  def show
    @group = Group.includes(:entities).find(params[:id])
    @entities = @group.entities.order(created_at: :desc)
    @total_amount = @group.entities.sum(:amount)
  end

  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private

  def set_group
    @group = current_user.groups.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<br />
<div class="group-item">
<%= form_with(model: @group, local: true) do |form| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% @group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

<div class="field">
  <%= form.label :icon %>
  <%= form.file_field :icon, accept: 'image/*' %>
</div>


  <div class="actions">
    <%= form.submit 'Submit' %> 
  </div>
<% end %>
</div>

app/views/groups/edit.html.erb
<%= render 'form', submit_label: 'Update category' %>

<br />

<%= link_to 'Back to groups', groups_path %>

app/views/groups/index.html.erb
<% if @groups.any? %>
  <ul class="groups-list">
    <% @groups.each do |group| %>
      <li class="group-item">
        <div class="group-details">

          <div class="group-i">
            <% if group.icon.attached? %>
              <%= image_tag group.icon, class: "group-icon" %>
            <% else %>
              <%= image_tag 'default.png', class: "group-icon" %>
            <% end %>
            
            <div class="group-inners">
              <%= link_to group.name, group_path(group), class: "group-name" %>
              <p class="group-created-at">
                <%= group.created_at.strftime('%Y-%m-%d %H:%M:%S') %>
              </p>
            </div>
          </div>

          <p class="group-info">
              <% currency = format_currency(group.entities.sum(:amount))%>
              <%= group.entities.count %> transactions <span><%= currency %></span>
          </p>
          </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="no-groups-message">No groups found for the current user.</p>
<% end %>
<div class = "new-group-link">
<%= link_to 'Add a new category', new_group_path, class: "new-group-link-inner" %>
<div>

<br>

app/views/groups/new.html.erb
<%= render 'form' %>

  <%= link_to 'All categories', groups_path %>

app/views/groups/show.html.erb
<div class="entity-detail">
  <div class="entity-i">
    <% if @group.icon.attached? %>
      <%= image_tag @group.icon, class: "group-icon" %>
    <% else %>
      <%= image_tag 'default.png', class: "group-icon" %>
    <% end %>
    <h1 class="group-name-nl"><%= @group.name %></h1>
  </div>

  <% if @group.entities.present? %>
    <table>
      <thead>
        <tr>
          <th>Transactions (<%= @group.entities.count %>)</th>
          <th>Amount</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        <% @entities.each do |entity| %>
          <tr>
            <td><%= link_to entity.name, entity_path(entity) %></td>
            <td><%= format_currency(entity.amount) %></td>
            <td><%= entity.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br />
    <h3 class="h3-title">Total Amount: <%= format_currency(@group.entities.sum(:amount)) %></h3>
  <% else %>
    <p>No transaction</p>
  <% end %>

  <br />
  <div>
    <% if @group.user == current_user %>
      <%= link_to 'Add transaction', new_entity_path(group_id: @group.id) %> |
      <%= link_to 'Edit', edit_group_path(@group) %> |
      <%= link_to 'Delete', group_path(@group), method: :delete, data: { confirm: 'Are you sure you want to delete this group?' } %>
    <% end %>
  </div>

  <%= link_to 'Back Categories', groups_path %>
</div>