config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  # ... other routes in your application

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "splash#index"

  resources :entities, only: [:index, :new, :create, :show, :destroy, :edit, :update, :all]

  resources :groups, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  resources :users, only: [:index, :new, :create, :show, :destroy, :edit, :update]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entities, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5 }, on: :create
  validates :email, presence: true, length: { minimum: 5 }, on: :create
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  validates :name, presence: true, length: { minimum: 5 }, allow_blank: { on: :update }
  validates :email, presence: true, length: { minimum: 5 }, allow_blank: { on: :update }
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: { on: :update }

  def user_groups
    groups.where(user_id: id).order(created_at: :desc)
  end

  def user_entities
    entities.where(user_id: id).order(created_at: :desc)
  end

  def self.most_recent(user, limit = 5)
    where(id: user.id).order(created_at: :desc).limit(limit)
  end

  def self.most_ancient(user, limit = 5)
    where(id: user.id).order(created_at: :asc).limit(limit)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password password_confirmation current_password])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  before_action :set_user, only: %i[show update destroy edit]

  rescue_from ActionController::InvalidAuthenticityToken, with: :handle_unauthorized

  def index
    @users = current_user.entities
  end

  def edit
    return if current_user == @user

    flash[:alert] = 'You are not authorized to edit this user.'
    redirect_to root_path
  end

  def show; end

  def update
    unless current_user == @user
      flash[:alert] = 'You are not authorized to update this user.'
      redirect_to root_path
      return
    end

    if @user.update(user_params)
      flash[:notice] = 'User was successfully updated.'
      redirect_to @user
    else
      flash[:alert] = "Error updating user: #{@user.errors.full_messages.join(', ')}"
      render :edit
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  def handle_unauthorized
    flash[:warning] = 'You are not authorized to access this resource. Please sign in.'
    redirect_to new_user_session_path
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- app/views/users/edit.html.erb -->
<h1>Edit Profile</h1>

<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>


  <div class="actions">
    <%= f.submit 'Update Profile', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back to profile', user_path(@user), class: 'btn btn-secondary' %>

app/views/users/index.html.erb
<h1>Your Entities</h1>

<% if @users.any? %>
  <ul class="entities-collections">
    <% @users.each do |entity| %>
      <%= link_to entity_path(entity) do %>
        <li class="entity">
          <% if entity.groups.any? %>
            <% group_icon = entity.groups.first.icon %>
            <%= image_tag(group_icon.present? ? group_icon : 'default.png', alt: 'GroupIcon', class: "group-icon") %> 
          <% else %>
            <%= image_tag 'default.png', alt: 'Default Icon', class: "group-icon" %>
          <% end %>
          <div>
            <div>
              <p><%= entity.name %></p> 
              <p><%= entity.amount %></p>
            </div>
            <p><%= entity.created_at.strftime('%Y-%m-%d %H:%M:%S') %></p>
          </div>
          <!-- <p>
          <% if entity.groups.any? %>
            <%= entity.groups.map { |group| link_to(group.name, group_path(group)) }.join(', ').html_safe %>
          <% end %>  
          -->
        </li>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <p>No entities found for the current user.</p>
<% end %>

<%= link_to 'New Entity', new_entity_path %>

app/views/users/show.html.erb
<br>
<div class="group-item">
<% unless @user == current_user %>
  <h2><%= @user.name %>'s Profile</h2>
<% end %>


<p>Name: <%= @user.name %></p>

<% if @user == current_user %>
    <p>Email: <%= @user.email %></p>
<% end %>

<p>Number of Categories: <%= @user.groups.count %></p>
<p>Number of transactions: <%= @user.entities.count %></p>
<p>Created at: <%= @user.created_at %></p>
</div>
<br>

<% if @user == current_user %>
    <%= link_to 'Edit Profile', edit_user_path(@user) %>
<% end %>

<%= link_to 'Back', entities_path %>

<br>